<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="김한울">
<meta name="dcterms.date" content="2025-11-19">
<meta name="description" content="AC U-Net REVIEW">

<title>paper review plan – Master Thesis Literature Review</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Master Thesis Literature Review</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.qmd"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-posts" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Posts</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-posts">    
        <li>
    <a class="dropdown-item" href="../../posts/index.html">
 <span class="dropdown-text">All posts</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">paper review plan</h1>
                  <div>
        <div class="description">
          AC U-Net REVIEW
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Plan</div>
                <div class="quarto-category">U-Net</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>김한울 </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">November 19, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#하단으로-내리면-리뷰어별-질문-및-대답-초안-작성해뒀습니다." id="toc-하단으로-내리면-리뷰어별-질문-및-대답-초안-작성해뒀습니다." class="nav-link active" data-scroll-target="#하단으로-내리면-리뷰어별-질문-및-대답-초안-작성해뒀습니다.">하단으로 내리면 리뷰어별 질문 및 대답 초안 작성해뒀습니다.</a></li>
  <li><a href="#검토-결과" id="toc-검토-결과" class="nav-link" data-scroll-target="#검토-결과">검토 결과</a></li>
  <li><a href="#종합-대응-전략-executive-summary" id="toc-종합-대응-전략-executive-summary" class="nav-link" data-scroll-target="#종합-대응-전략-executive-summary">1. 종합 대응 전략 (Executive Summary)</a></li>
  <li><a href="#상세-대응-계획-action-plan" id="toc-상세-대응-계획-action-plan" class="nav-link" data-scroll-target="#상세-대응-계획-action-plan">2. 상세 대응 계획 (Action Plan)</a>
  <ul class="collapse">
  <li><a href="#a.-추가-실험-experiments" id="toc-a.-추가-실험-experiments" class="nav-link" data-scroll-target="#a.-추가-실험-experiments">A. 추가 실험 (Experiments)</a></li>
  <li><a href="#b.-시각화-및-해석-visualization-interpretation" id="toc-b.-시각화-및-해석-visualization-interpretation" class="nav-link" data-scroll-target="#b.-시각화-및-해석-visualization-interpretation">B. 시각화 및 해석 (Visualization &amp; Interpretation)</a></li>
  <li><a href="#c.-원고-수정-manuscript-revision" id="toc-c.-원고-수정-manuscript-revision" class="nav-link" data-scroll-target="#c.-원고-수정-manuscript-revision">C. 원고 수정 (Manuscript Revision)</a></li>
  </ul></li>
  <li><a href="#리뷰어별-답변-예상" id="toc-리뷰어별-답변-예상" class="nav-link" data-scroll-target="#리뷰어별-답변-예상">3. 리뷰어별 답변 예상?</a>
  <ul class="collapse">
  <li><a href="#to-reviewer-1" id="toc-to-reviewer-1" class="nav-link" data-scroll-target="#to-reviewer-1">To Reviewer 1</a></li>
  <li><a href="#to-reviewer-2" id="toc-to-reviewer-2" class="nav-link" data-scroll-target="#to-reviewer-2">To Reviewer 2</a></li>
  </ul></li>
  <li><a href="#리뷰-원문-및-대응-초안" id="toc-리뷰-원문-및-대응-초안" class="nav-link" data-scroll-target="#리뷰-원문-및-대응-초안">리뷰 원문 및 대응 초안</a>
  <ul class="collapse">
  <li><a href="#reviewer-1" id="toc-reviewer-1" class="nav-link" data-scroll-target="#reviewer-1">Reviewer: 1</a>
  <ul class="collapse">
  <li><a href="#comments-to-the-author" id="toc-comments-to-the-author" class="nav-link" data-scroll-target="#comments-to-the-author">Comments to the Author</a></li>
  </ul></li>
  <li><a href="#reviewer-2" id="toc-reviewer-2" class="nav-link" data-scroll-target="#reviewer-2">Reviewer: 2</a>
  <ul class="collapse">
  <li><a href="#comments-to-the-author-1" id="toc-comments-to-the-author-1" class="nav-link" data-scroll-target="#comments-to-the-author-1">Comments to the Author</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="하단으로-내리면-리뷰어별-질문-및-대답-초안-작성해뒀습니다." class="level1">
<h1>하단으로 내리면 리뷰어별 질문 및 대답 초안 작성해뒀습니다.</h1>
<section id="베이스라인-비교-실험-결과" class="level4">
<h4 class="anchored" data-anchor-id="베이스라인-비교-실험-결과">베이스라인 비교 실험 결과</h4>
<ul>
<li>CONVLSTM, HRNet 실험 종료</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Time</th>
<th>AC U-Net(2021~2023)</th>
<th>HRNet(2021~2023)</th>
<th>convLSTM(2021~2023)</th>
<th>persistence(2021~2023)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>30min</td>
<td>Avg MSE: 0.0250,<br> Avg MAE: 0.0918, <br> Avg PSNR: 23.28, <br> Avg SSIM: 0.6220</td>
<td>Avg MSE: 0.0263, <br> Avg MAE: 0.0961, <br> Avg PSNR: 22.96, <br> Avg SSIM: 0.5941</td>
<td>Avg MSE: 0.0413, <br> Avg MAE: 0.1359, <br> Avg PSNR: 20.73, <br> Avg SSIM: 0.5630</td>
<td>Avg MSE: 0.0552, <br> Avg MAE: 0.1609, <br> Avg PSNR: 19.43, <br> Avg SSIM: 0.5329</td>
</tr>
<tr class="even">
<td>60min</td>
<td>Avg MSE: 0.0340, <br> Avg MAE: 0.1159, <br> Avg PSNR: 21.77, <br> Avg SSIM: 0.5853</td>
<td>Avg MSE: 0.0364, <br> Avg MAE: 0.1177, <br> Avg PSNR: 21.51, <br> Avg SSIM: 0.5824</td>
<td>Avg MSE: 0.0650, <br> Avg MAE: 0.0881, <br> Avg PSNR: 18.53, <br> Avg SSIM: 0.5264</td>
<td>Avg MSE: 0.0961, <br> Avg MAE: 0.2275, <br> Avg PSNR: 17.06, <br> Avg SSIM: 0.4904</td>
</tr>
<tr class="odd">
<td>90min</td>
<td>Avg MSE: 0.0425, <br> Avg MAE: 0.1328, <br> Avg PSNR: 20.81, <br> Avg SSIM: 0.5781</td>
<td>Avg MSE: 0.0465, <br> Avg MAE: 0.1373, <br> Avg PSNR: 20.45, <br> Avg SSIM: 0.5574</td>
<td>Avg MSE: 0.0890, <br> Avg MAE: 0.2357, <br> Avg PSNR: 17.08, <br> Avg SSIM: 0.5112</td>
<td>Avg MSE: 0.1388, <br> Avg MAE: 0.2814, <br> Avg PSNR: 15.61, <br> Avg SSIM: 0.4641</td>
</tr>
<tr class="even">
<td>120min</td>
<td>Avg MSE: 0.0510, <br> Avg MAE: 0.1467, <br> Avg PSNR: 20.02, <br> Avg SSIM: 0.5721</td>
<td>Avg MSE: 0.0570, <br> Avg MAE: 0.1572, <br> Avg PSNR: 19.60, <br> Avg SSIM: 0.5743</td>
<td>Avg MSE: 0.1189, <br> Avg MAE: 0.2829, <br> Avg PSNR: 15.93, <br> Avg SSIM: 0.5078</td>
<td>Avg MSE: 0.1791, <br> Avg MAE: 0.3246, <br> Avg PSNR: 14.61, <br> Avg SSIM: 0.4452</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="검토-결과" class="level1">
<h1>검토 결과</h1>
<p>두 리뷰어 모두 <strong>비교 모델(Baseline)의 부족</strong>과 <strong>정성적 결과(Blurriness)에 대한 과장된 주장</strong>을 지적하고 있습니다.</p>
</section>
<section id="종합-대응-전략-executive-summary" class="level1">
<h1>1. 종합 대응 전략 (Executive Summary)</h1>
<ul>
<li><strong>우선순위 1 (실험):</strong> <strong>ConvLSTM</strong>과 <strong>HRNet</strong> (또는 유사 SOTA 모델)을 구현하여 비교 실험 수행. (가장 중요)</li>
<li><strong>우선순위 2 (분석):</strong> <strong>Ablation Study 강화</strong>. 기존의 Feature 유무뿐만 아니라, 모듈(CBAM, FiLM)의 유무에 따른 성능 변화 분석 추가.</li>
<li><strong>우선순위 3 (시각화):</strong> <strong>Figure 2 (예측 결과) 개선</strong>. Grayscale 대신 Colormap(Jet/Plasma 등)을 사용하여 가시성 확보 및 Attention Map 시각화 추가.</li>
<li><strong>우선순위 4 (텍스트):</strong> “Blurriness가 해결되었다”는 과장된 표현을 “완화되었으나 여전히 도전적인 과제임”으로 수정하고, 입력 변수 정의(<span class="math inline">\(\Delta t_{ref}\)</span>)를 명확히 기술.</li>
</ul>
<hr>
</section>
<section id="상세-대응-계획-action-plan" class="level1">
<h1>2. 상세 대응 계획 (Action Plan)</h1>
<section id="a.-추가-실험-experiments" class="level2">
<h2 class="anchored" data-anchor-id="a.-추가-실험-experiments">A. 추가 실험 (Experiments)</h2>
<ol type="1">
<li><strong>Baseline 모델 추가 (R1-1, R2-1)</strong>
<ul>
<li><strong>대응:</strong> <code>ConvLSTM</code>과 <code>HRNet</code> 모델을 구현하여 동일한 데이터셋으로 학습 및 평가.</li>
<li><strong>코드 수정 필요:</strong> 새로운 모델 클래스 파일 생성 필요. 기존 <code>main_ablation.py</code> 구조를 활용하되 모델만 교체하여 학습.</li>
<li><strong>예상 결과:</strong> AC U-Net이 ConvLSTM보다는 확실히 좋고, HRNet과는 비슷하거나 장기 예측(120분)에서 더 우수함을 보여주어야 함.</li>
</ul></li>
<li><strong>상세 Ablation Study (R1-2)</strong>
<ul>
<li><strong>대응:</strong> 기존에는 Feature(<span class="math inline">\(F_{GLCM}, F_{SE}\)</span>) 유무만 비교했으나, 아키텍처 요소인 <strong>CBAM</strong>과 <strong>FiLM</strong> 모듈 자체의 유무에 따른 성능 변화 실험 필요.</li>
<li><strong>코드 수정:</strong> <code>model_gg.py</code>의 <code>UNetWithGLCM</code> 클래스에 <code>use_cbam</code>, <code>use_film</code> 플래그를 추가하여 모듈을 On/Off 할 수 있게 수정.</li>
</ul></li>
<li><strong>Inference Latency 측정 (R1-6)</strong>
<ul>
<li><strong>대응:</strong> 테스트 셋에 대해 모델별 평균 추론 시간(ms) 측정.</li>
<li><strong>코드 수정:</strong> <code>engine_gg_ablation.py</code>의 <code>test_and_save_results</code> 함수 내에 시간 측정 코드(<code>torch.cuda.Event</code> 활용) 추가.</li>
</ul></li>
</ol>
</section>
<section id="b.-시각화-및-해석-visualization-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="b.-시각화-및-해석-visualization-interpretation">B. 시각화 및 해석 (Visualization &amp; Interpretation)</h2>
<ol type="1">
<li><strong>Figure 개선 (R2-5)</strong>
<ul>
<li><strong>대응:</strong> 흑백 이미지는 대비가 낮아 구름 구분이 어려움. Pseudo-color (예: <code>plt.cm.jet</code> or <code>inferno</code>)를 적용하고 <code>vmin</code>, <code>vmax</code>를 고정하여 시각화.</li>
<li><strong>코드 수정:</strong> <code>engine_gg_ablation.py</code> 내 이미지 저장 부분 수정.</li>
</ul></li>
<li><strong>Interpretability (R1-5)</strong>
<ul>
<li><strong>대응:</strong> CBAM 모듈의 Spatial Attention Map을 추출하여 입력 이미지 위에 히트맵으로 오버레이. 모델이 구름의 가장자리나 이동 방향에 집중하고 있음을 시각적으로 제시.</li>
</ul></li>
</ol>
</section>
<section id="c.-원고-수정-manuscript-revision" class="level2">
<h2 class="anchored" data-anchor-id="c.-원고-수정-manuscript-revision">C. 원고 수정 (Manuscript Revision)</h2>
<ol type="1">
<li><strong>Blurriness 주장 완화 (R2-2)</strong>
<ul>
<li><em>Introduction/Conclusion:</em> “Solved blurry images” -&gt; “Significantly reduced blurring artifacts compared to baselines, improving structural consistency via MS-SSIM, although resolving high-frequency details in rapidly evolving clouds remains a challenge.” 로 톤 다운.</li>
</ul></li>
<li><strong>입력 변수 정의 명확화 (R2-3)</strong>
<ul>
<li><span class="math inline">\(\Delta t_{ref}\)</span>에 대한 수식적 정의 추가.</li>
<li><em>코드 분석 결과:</em> 코드를 보면 <code>pw_ref_idx = last_input_idx - (self.lp + 1)</code>로 되어 있습니다. 즉, 예측하고자 하는 미래 시점(<span class="math inline">\(t+j\)</span>)과의 간격만큼 과거 시점(<span class="math inline">\(t-j\)</span>)을 참조하여 변화량을 계산하는 방식입니다. 이를 논문에 명시해야 합니다.</li>
</ul></li>
<li><strong>지리적/지형적 논의 (R1-3, R2-4)</strong>
<ul>
<li>제주도/대마도 에러 원인을 “지형 정보(DEM)의 부재”와 “해양-육지 경계의 복잡성”으로 구체화.</li>
<li>한국 외 지역 적용 가능성(Generalization)에 대해 Discussion 섹션에 언급 (데이터만 있으면 구조는 동일하게 적용 가능).</li>
</ul></li>
</ol>
<hr>
</section>
</section>
<section id="리뷰어별-답변-예상" class="level1">
<h1>3. 리뷰어별 답변 예상?</h1>
<section id="to-reviewer-1" class="level2">
<h2 class="anchored" data-anchor-id="to-reviewer-1">To Reviewer 1</h2>
<ul>
<li><p><strong>Q1 (Baseline):</strong> “제안해주신 대로 ConvLSTM과 HRNet을 추가 실험하였으며, 결과를 Table X에 추가했습니다.”</p>
<ul>
<li>특히 장기 예측(120분)에서 더 우수한 성능이 나오면 좋겠다</li>
</ul></li>
<li><p><strong>Q2 (Detailed Ablation):</strong> “CBAM과 FiLM의 기여도를 분리하여 분석한 표를 추가했습니다. FiLM이 계절적 맥락을 주입하는 데 핵심적임을 확인했습니다.”</p></li>
<li><p><strong>Q3 (Geography):</strong> “한국으로 한정된 점은 인정하나, 제안 방법론(Texture/Seasonal conditioning)은 지역 무관한 특성임을 Discussion에 추가했습니다.”</p></li>
<li><p><strong>Q4 (Citations):</strong> “언급해주신 DSIA U-Net, AER U-Net을 Related Work에 포함하여 Attention 메커니즘의 발전 흐름을 보강했습니다.”</p></li>
<li><p><strong>Q5 (Interpretability):</strong> “Attention map 시각화를 통해 모델이 구름의 경계선(edge)에 집중함을 보여주는 Figure Y를 추가했습니다.”</p></li>
<li><p><strong>Q6 (Latency):</strong> “추론 시간을 측정한 결과, U-Net 대비 약간 증가했으나(약 X ms), 실시간 운영(30분 간격)에는 충분함을 논의했습니다.”</p></li>
</ul>
</section>
<section id="to-reviewer-2" class="level2">
<h2 class="anchored" data-anchor-id="to-reviewer-2">To Reviewer 2</h2>
<ul>
<li><p><strong>Q1 (Baseline):</strong> (Reviewer 1과 동일하게 ConvLSTM, HRNet 추가 결과를 제시하며 방어). “강력한 Baseline과의 비교를 통해 모델의 유효성을 입증했습니다.”</p></li>
<li><p><strong>Q2 (Blurriness):</strong> “지적해주신 대로 완벽한 해결은 아니며 과장된 표현이었음을 인정합니다. 텍스트를 수정하여 ’구조적 일관성 개선’에 초점을 맞췄고, 한계점(Limitation) 섹션에 고주파 디테일 복원의 어려움을 명시했습니다.”</p></li>
<li><p><strong>Q3 (Input Feature):</strong> “<span class="math inline">\(\Delta t_{ref}\)</span>는 예측 시점(Lead time)에 비례하여 설정됨을 수식으로 명확히 했습니다.”</p></li>
<li><p><strong>Q4 (Micro-climate):</strong> “지형 데이터(Elevation map)가 입력으로 사용되지 않아, 지형에 의한 국지적 구름 생성/소멸을 예측하는 데 한계가 있음을 분석에 추가했습니다.”</p></li>
<li><p><strong>Q5 (Visualization):</strong> “그림의 가시성을 높이기 위해 Pseudo-color 맵을 적용하여 수정했습니다.”</p></li>
</ul>
<hr>
</section>
</section>
<section id="리뷰-원문-및-대응-초안" class="level1">
<h1>리뷰 원문 및 대응 초안</h1>
<p>Reviewer(s) Comments:</p>
<section id="reviewer-1" class="level2">
<h2 class="anchored" data-anchor-id="reviewer-1">Reviewer: 1</h2>
<section id="comments-to-the-author" class="level3">
<h3 class="anchored" data-anchor-id="comments-to-the-author">Comments to the Author</h3>
<p>This paper proposes AC U-Net, an enhanced U-Net architecture incorporating spatiotemporal attention and conditional feature modulation (FiLM) for multi-step solar irradiance forecasting using GK-2A satellite imagery over Korea. By integrating texture and seasonal contextual embeddings, the model achieves notable improvements in accuracy (16.8% MSE reduction at 120-min horizon) compared to the baseline U-Net and Persistence models.</p>
<ol type="1">
<li>The paper only compares AC U-Net with the Persistence and U-Net baselines. Including additional recent architectures such as ConvLSTM, HRNet, Transformer-based models, or Gener</li>
</ol>
<blockquote class="blockquote">
<p>Thank you for your valuable suggestion. We agree that comparing our model with stronger, state-of-the-art baselines is essential to validate its performance. In response to your comment, we have implemented and evaluated <strong>ConvLSTM</strong> and <strong>HRNet</strong>, which are widely recognized benchmarks in spatiotemporal forecasting and high-resolution representation learning, respectively.</p>
</blockquote>
<blockquote class="blockquote">
<p>We have updated the experimental results (Table 2 in the revised manuscript) to include these models using the full test dataset from 2021 to 2023. As shown in the table below, <strong>AC U-Net consistently outperforms both ConvLSTM and HRNet across all lead times.</strong></p>
</blockquote>
<blockquote class="blockquote">
<ul>
<li><strong>Comparison with HRNet:</strong> While HRNet performs competitively due to its ability to maintain high-resolution representations, AC U-Net achieves better accuracy. For instance, at the 120-minute horizon, AC U-Net reduces the MSE by approximately <strong>10.5%</strong> compared to HRNet (0.0510 vs.&nbsp;0.0570) and achieves a higher SSIM (0.5721 vs.&nbsp;0.5743). This demonstrates that our proposed contextual embedding strategy (FiLM) effectively complements spatial feature extraction.</li>
<li><strong>Comparison with ConvLSTM:</strong> AC U-Net significantly outperforms ConvLSTM across all metrics. At the 120-minute horizon, our model reduces the MSE by <strong>57.1%</strong> (0.0510 vs.&nbsp;0.1189) and improves PSNR by roughly 4 dB (20.02 vs.&nbsp;15.93). This indicates that our architecture is more robust in capturing long-term dynamics compared to the recurrent structure of ConvLSTM for this specific task.</li>
</ul>
</blockquote>
<blockquote class="blockquote">
<p>We have reflected these results in the revised manuscript to strengthen the validation of our proposed method.</p>
</blockquote>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Lead Time</th>
<th style="text-align: center;">Metric</th>
<th style="text-align: center;"><strong>AC U-Net</strong></th>
<th style="text-align: center;">HRNet</th>
<th style="text-align: center;">ConvLSTM</th>
<th style="text-align: center;">Persistence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>30 min</strong></td>
<td style="text-align: center;">MSE</td>
<td style="text-align: center;"><strong>0.0250</strong></td>
<td style="text-align: center;">0.0263</td>
<td style="text-align: center;">0.0413</td>
<td style="text-align: center;">0.0552</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">SSIM</td>
<td style="text-align: center;"><strong>0.6220</strong></td>
<td style="text-align: center;">0.5941</td>
<td style="text-align: center;">0.5630</td>
<td style="text-align: center;">0.5329</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>120 min</strong></td>
<td style="text-align: center;">MSE</td>
<td style="text-align: center;"><strong>0.0510</strong></td>
<td style="text-align: center;">0.0570</td>
<td style="text-align: center;">0.1189</td>
<td style="text-align: center;">0.1791</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">SSIM</td>
<td style="text-align: center;">0.5721</td>
<td style="text-align: center;"><strong>0.5743</strong></td>
<td style="text-align: center;">0.5078</td>
<td style="text-align: center;">0.4452</td>
</tr>
</tbody>
</table>
<ol start="2" type="1">
<li><p>The ablation focuses mainly on contextual feature combinations (FGLCM and FSE). However, a more detailed analysis isolating the impact of FiLM, CBAM, and spatiotemporal attentioative Diffusion Networks (as hinted in the conclusion) would strengthen the validation of the proposed method’s superiority. n modules would help attribute performance gains more clearly to architectural innovations.</p></li>
<li><p>The study is geographically restricted to the Korean Peninsula, which may limit global applicability. The authors should discuss potential generalization issues or validate the model on data from other regions or satellite sources (e.g., Himawari, GOES).</p></li>
<li><p>The authors are encouraged to include recent attention-based U-Net variants such as “DSIA U-Net: Deep Shallow Interaction with Attention Mechanism U-Net for Remote Sensing Satellite Images” and “AER U-Net: Attention-Enhanced Multi-Scale Residual U-Net Structure for Water Body Segmentation Using Sentinel-2 Satellite Images” in the Related Work section. These models demonstrate effective strategies for integrating multi-scale attention and contextual feature interactions, which are conceptually aligned with the proposed AC U-Net. Citing and briefly comparing these works (around the discussion of attention-enhanced U-Net methods, Section II, lines 10–20) would better position this study within the broader evolution of attention-driven U-Net architectures and strengthen the motivation for introducing the spatiotemporal attention and FiLM-based feature modulation.</p></li>
<li><p>While the model performs well, interpretability is limited. The paper would benefit from an analysis linking model attention maps or feature activations to physical cloud dynamics, enhancing scientific insight beyond numerical improvement.</p></li>
<li><p>Training requires 12.9 hours per model, which may be impractical for operational forecasting. The authors should discuss inference latency, computational requirements, and possible trade-offs between accuracy and efficiency for real-time deployment.</p></li>
</ol>
<blockquote class="blockquote">
<p>Although the proposed AC U-Net requires approximately 12.9 hours for training per lead time, this is an offline process typically performed periodically (monthly, or quarterly) to update model weights. For real-time operational forecasting, the critical constraint is inference latency. To validte the model’s suitability for real-time deployment, we benchmarked the inference speed on an L40S GPU. The results show an average inference latency of 26.46 ms ± 3.64 ms per sample, corresponding to a throughput of approximately 37.8 FPS. This low latency demonstrates that the model can generate forecasts almost instantaneously upon receiving new satellite imagery. Consequently, the high computational cost of training does not hinder the model’s operational utility, as the inference process is highly efficient and scalable for real-time applications.</p>
</blockquote>
</section>
</section>
<section id="reviewer-2" class="level2">
<h2 class="anchored" data-anchor-id="reviewer-2">Reviewer: 2</h2>
<section id="comments-to-the-author-1" class="level3">
<h3 class="anchored" data-anchor-id="comments-to-the-author-1">Comments to the Author</h3>
<section id="major-comments" class="level4">
<h4 class="anchored" data-anchor-id="major-comments">Major Comments:</h4>
<p>1: Selection of Baseline Models: The comparison is limited to only the Persistence model and a standard U-Net, which feels somewhat insufficient for this study. In the field of spatiotemporal forecasting, models such as ConvLSTM and HRNet are recognized as strong baselines. The authors have not included these in their comparison. While acknowledging the space constraints of a Letter, the authors should at least discuss in the text (e.g., in the “Experimental Setup” or “Conclusion” section) why these models were not selected for comparison, or acknowledge this as a limitation. This would add to the rigor of the study.</p>
<blockquote class="blockquote">
<p>We appreciate your constructive feedback regarding the selection of baseline models. We acknowledge that comparing only with Persistence and standard U-Net was insufficient to fully demonstrate the superiority of our proposed method. To address this rigor issue directly, <strong>we have conducted additional comparative experiments using ConvLSTM and HRNet</strong>, rather than simply discussing their exclusion. The new experimental results, obtained from the 2021–2023 test set, have been added to the revised manuscript. The results confirm that AC U-Net provides the most accurate forecasts: 1. <strong>AC U-Net vs.&nbsp;HRNet:</strong> HRNet showed strong performance, ranking second best. However, AC U-Net consistently achieved lower error rates. Specifically, at the 120-minute lead time, AC U-Net recorded an MSE of <strong>0.0510</strong>, which is superior to HRNet’s <strong>0.0570</strong>. This suggests that injecting global context (seasonal and texture features) via our proposed FiLM layer provides a distinct advantage over HRNet’s multi-scale fusion approach for solar irradiance forecasting.<br>
2. <strong>AC U-Net vs.&nbsp;ConvLSTM:</strong> ConvLSTM showed limitations in preserving structural details and long-term accuracy, recording significantly higher MSE (0.1189 at 120 min) and lower PSNR/SSIM scores compared to AC U-Net.<br>
We have updated the <strong>“Experimental Results”</strong> section to include these comparisons, providing a more rigorous validation of our model’s effectiveness against established spatiotemporal forecasting baselines.</p>
</blockquote>
<p>2: Issue of Blurry Predictions: The authors state in the introduction that a key problem with existing models (e.g., ConvLSTM) is the generation of “over-smoothed outputs” or “blurry images.” However, the qualitative results (Fig. 2) show that the proposed AC U-Net also produces clearly smoothed and blurry predictions in complex scenarios (e.g., Jan 22nd and July 25th), especially as the forecast horizon increases. A significant amount of high-frequency texture detail is lost. While the authors acknowledge this in their analysis, the introduction and conclusion seem to imply that the new model has resolved this issue. This appears to be an overstatement. The authors should provide a more objective assessment of the model’s true performance regarding the “blurriness problem.”</p>
<blockquote class="blockquote">
<p>We sincerely thank the reviewer for this insightful observation. We fully agree that stating our model has “resolved” the blurriness problem was an overstatement. As correctly pointed out, while AC U-Net improves structural fidelity compared to baselines, it still exhibits smoothing effects, particularly in complex scenarios and at longer forecast horizons due to the inherent uncertainty of future cloud dynamics and the nature of the regression loss functions employed. To address this, we have made the following revisions to the manuscript: 1. <strong>Revised Claims:</strong> We have toned down the language in the <strong>Introduction</strong> and <strong>Conclusion</strong>. Instead of claiming to have “solved” the issue, we now state that our method <em>“mitigates over-smoothing and improves the preservation of structural details compared to standard baselines.”</em><br>
2. <strong>Objective Assessment:</strong> In the <strong>“Qualitative Analysis”</strong> section, we have added a candid discussion acknowledging that high-frequency texture details are still lost in challenging cases (e.g., Jan 22nd and July 25th). We explicitly mention that while the MS-SSIM loss helps maintain structural coherence, recovering fine-grained textures remains a challenging open problem.<br>
3. <strong>Limitations Section:</strong> We have expanded the <strong>Conclusion (or Discussion)</strong> to include a limitation regarding the “blurriness problem,” suggesting that future work incorporating Diffusion Probabilistic Models could further address this issue by generating more realistic high-frequency details.</p>
</blockquote>
</section>
<section id="minor-comments" class="level4">
<h4 class="anchored" data-anchor-id="minor-comments">Minor Comments:</h4>
<p>1: Ambiguous Definition of Input Features: When describing the Power Feature and Sobel Power Feature, the paper states the time lag (Δtref) is “set by the time lag between It and Yt+j”. This definition is vague. How is this time lag specifically defined? How is it set according to the prediction step j?</p>
<p>2: In Fig. 3, the authors identify that high-error regions are concentrated over Jeju and Tsushima islands, attributing this to “terrain-driven micro-climates.” This is a good finding. However, the term “micro-climate” alone is somewhat insufficient. It is recommended that the authors add a brief sentence explaining why the model struggles to capture these micro-climates (e.g., is it due to a lack of static topographical/elevation data as input?)</p>
<p>3: As the primary qualitative result, the images in Fig. 2 (particularly the case for March 30th) suffer from very low contrast, making details difficult to discern. It is suggested that the authors adjust the image contrast or apply pseudo-color (without altering the underlying data) to allow reviewers and readers to more clearly evaluate the predicted cloud structures.</p>


</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>