<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="김한울">
<meta name="dcterms.date" content="2026-07-03">

<title>Master Thesis Literature Review - Biomechanical Evaluation of Spatiotemporal Gait Parameters in Parkinson’s Disease: A Standardized 6-Meter Walk-Through Study</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Master Thesis Literature Review</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
<span class="menu-text">Home</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../about.qmd">
<span class="menu-text">About</span></a>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-posts" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Posts</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-posts">
        <li>
    <a class="dropdown-item" href="../../posts/index.html">
 <span class="dropdown-text">All posts</span></a>
  </li>
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Biomechanical Evaluation of Spatiotemporal Gait Parameters in Parkinson’s Disease: A Standardized 6-Meter Walk-Through Study</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">vesti_memo</div>
              </div>
                  </div>
  </div>


  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>김한울 </p>
            </div>
    </div>

      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">July 3, 2026</p>
      </div>
    </div>


    </div>


  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>

  <ul>
  <li><a href="#biomechanical-evaluation-of-spatiotemporal-gait-parameters-in-parkinsons-disease-a-standardized-6-meter-walk-through-study" id="toc-biomechanical-evaluation-of-spatiotemporal-gait-parameters-in-parkinsons-disease-a-standardized-6-meter-walk-through-study" class="nav-link active" data-scroll-target="#biomechanical-evaluation-of-spatiotemporal-gait-parameters-in-parkinsons-disease-a-standardized-6-meter-walk-through-study">Biomechanical Evaluation of Spatiotemporal Gait Parameters in Parkinson’s Disease: A Standardized 6-Meter Walk-Through Study</a>
  <ul class="collapse">
  <li><a href="#study-cohort-demographic-distribution" id="toc-study-cohort-demographic-distribution" class="nav-link" data-scroll-target="#study-cohort-demographic-distribution">1. Study Cohort &amp; Demographic Distribution</a></li>
  <li><a href="#methodology-statistical-analysis" id="toc-methodology-statistical-analysis" class="nav-link" data-scroll-target="#methodology-statistical-analysis">2. Methodology &amp; Statistical Analysis</a>
  <ul class="collapse">
  <li><a href="#이중-가설-검정-구조-trial-level-subject-level-dual-structure" id="toc-이중-가설-검정-구조-trial-level-subject-level-dual-structure" class="nav-link" data-scroll-target="#이중-가설-검정-구조-trial-level-subject-level-dual-structure">2-1. 이중 가설 검정 구조 (Trial-level &amp; Subject-level Dual Structure)</a></li>
  <li><a href="#통계-검정-및-효과-크기-평측-방법" id="toc-통계-검정-및-효과-크기-평측-방법" class="nav-link" data-scroll-target="#통계-검정-및-효과-크기-평측-방법">2-2. 통계 검정 및 효과 크기 평측 방법</a></li>
  </ul></li>
  <li><a href="#results-통계-검정-결과" id="toc-results-통계-검정-결과" class="nav-link" data-scroll-target="#results-통계-검정-결과">3. Results (통계 검정 결과)</a>
  <ul class="collapse">
  <li><a href="#table-1.-trial-level-comparison-primary-analysis-n233-trials" id="toc-table-1.-trial-level-comparison-primary-analysis-n233-trials" class="nav-link" data-scroll-target="#table-1.-trial-level-comparison-primary-analysis-n233-trials">Table 1. Trial-Level Comparison (Primary Analysis, <span class="math inline">\(N=233\)</span> trials)</a></li>
  <li><a href="#table-2.-subject-level-comparison-sensitivity-analysis-random-1-pick-n98-subjects" id="toc-table-2.-subject-level-comparison-sensitivity-analysis-random-1-pick-n98-subjects" class="nav-link" data-scroll-target="#table-2.-subject-level-comparison-sensitivity-analysis-random-1-pick-n98-subjects">Table 2. Subject-Level Comparison (Sensitivity Analysis, Random 1-Pick, <span class="math inline">\(N=98\)</span> subjects)</a></li>
  <li><a href="#각-변수별-가설-검정-결과의-통계적-상세-기술" id="toc-각-변수별-가설-검정-결과의-통계적-상세-기술" class="nav-link" data-scroll-target="#각-변수별-가설-검정-결과의-통계적-상세-기술">3-1. 각 변수별 가설 검정 결과의 통계적 상세 기술</a></li>
  <li><a href="#가설-검정-결과-테이블의-총체적-해석" id="toc-가설-검정-결과-테이블의-총체적-해석" class="nav-link" data-scroll-target="#가설-검정-결과-테이블의-총체적-해석">3-2. 가설 검정 결과 테이블의 총체적 해석</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">4. Discussion</a>
  <ul class="collapse">
  <li><a href="#공간적spatial-결함의-확실성-및-대수적-인과관계-규명" id="toc-공간적spatial-결함의-확실성-및-대수적-인과관계-규명" class="nav-link" data-scroll-target="#공간적spatial-결함의-확실성-및-대수적-인과관계-규명">4-1. 공간적(Spatial) 결함의 확실성 및 대수적 인과관계 규명</a></li>
  <li><a href="#이중-분석dual-level-analysis의-가치-및-보행-속도의-경계선-유의미성" id="toc-이중-분석dual-level-analysis의-가치-및-보행-속도의-경계선-유의미성" class="nav-link" data-scroll-target="#이중-분석dual-level-analysis의-가치-및-보행-속도의-경계선-유의미성">4-2. 이중 분석(Dual-level Analysis)의 가치 및 보행 속도의 경계선 유의미성</a></li>
  <li><a href="#stride-time-cv의-통계적-null-결과와-방향성-전도-현상" id="toc-stride-time-cv의-통계적-null-결과와-방향성-전도-현상" class="nav-link" data-scroll-target="#stride-time-cv의-통계적-null-결과와-방향성-전도-현상">4-3. Stride Time CV의 통계적 Null 결과와 방향성 전도 현상</a></li>
  <li><a href="#initiation-delay-null-결과의-설계적-해석" id="toc-initiation-delay-null-결과의-설계적-해석" class="nav-link" data-scroll-target="#initiation-delay-null-결과의-설계적-해석">4-4. Initiation Delay Null 결과의 설계적 해석</a></li>
  </ul></li>
  <li><a href="#conclusion-future-work-결론-및-향후-보완-방향" id="toc-conclusion-future-work-결론-및-향후-보완-방향" class="nav-link" data-scroll-target="#conclusion-future-work-결론-및-향후-보완-방향">5. Conclusion &amp; Future Work (결론 및 향후 보완 방향)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="biomechanical-evaluation-of-spatiotemporal-gait-parameters-in-parkinsons-disease-a-standardized-6-meter-walk-through-study" class="level1">
<h1>Biomechanical Evaluation of Spatiotemporal Gait Parameters in Parkinson’s Disease: A Standardized 6-Meter Walk-Through Study</h1>
<hr>
<section id="study-cohort-demographic-distribution" class="level2">
<h2 class="anchored" data-anchor-id="study-cohort-demographic-distribution">1. Study Cohort &amp; Demographic Distribution</h2>
<p>본 연구는 다기관 협력 연구 데이터베이스(UNIST, 울산대병원, 전북대병원)에서 수집된 보행 시점 데이터를 기반으로 수행되었습니다. 임상 마스터 테이블(<code>cleaned_clinical_crf.csv</code>)의 임상 데이터 품질 통과 기준(Grade ‘O’) 및 모션 데이터 파일(.trc 및 .mot 파일의 쌍)이 온전하게 매칭되는 233개의 보행 데이터셋을 최종 분석 대상으로 확정하였습니다.</p>
<p>집단별 고유 피험자(Subject) 수와 총 분석 대상 시도(Trial) 수의 상세 분포는 다음과 같습니다: * <strong>Healthy Control (정상 대조군, HC)</strong>: * <span class="math inline">\(N_{\text{subject}} = 21\)</span> 명 * <span class="math inline">\(N_{\text{trial}} = 40\)</span> trials (피험자당 평균 <span class="math inline">\(1.90\)</span>회 수행) * <strong>Parkinson’s Disease (파킨슨병 환자군, PD)</strong>: * <span class="math inline">\(N_{\text{subject}} = 77\)</span> 명 * <span class="math inline">\(N_{\text{trial}} = 193\)</span> trials (피험자당 평균 <span class="math inline">\(2.51\)</span>회 수행) * <strong>Total Dataset</strong>: <span class="math inline">\(N_{\text{subject}} = 98\)</span> 명, <span class="math inline">\(N_{\text{trial}} = 233\)</span> trials</p>
<hr>
</section>
<section id="methodology-statistical-analysis" class="level2">
<h2 class="anchored" data-anchor-id="methodology-statistical-analysis">2. Methodology &amp; Statistical Analysis</h2>
<section id="이중-가설-검정-구조-trial-level-subject-level-dual-structure" class="level3">
<h3 class="anchored" data-anchor-id="이중-가설-검정-구조-trial-level-subject-level-dual-structure">2-1. 이중 가설 검정 구조 (Trial-level &amp; Subject-level Dual Structure)</h3>
<p>다기관 반복 측정 데이터의 독립성 위배 문제를 방어하고 통계적 강건성을 다각도로 검증하기 위해, 본 연구는 <strong>시도 단위 분석(Trial-level primary analysis)</strong>과 <strong>피험자 단위 분석(Subject-level sensitivity analysis)</strong>의 이중 검정 구조를 채택하였습니다. 1. <strong>Trial-Level Primary Analysis (표본 크기: <span class="math inline">\(N=233\)</span> [HC=40, PD=193])</strong>: * 각 피험자가 수행한 개별 6m 보행 시도를 독립된 관측치로 취급하여 검정을 수행합니다. 반복 측정의 상관관계가 존재할 수 있어 검정력이 과대 추정될 수 있는 한계가 있지만, 개별 보행 거동의 미세 변동성을 모두 보존하여 평가할 수 있습니다. 2. <strong>Subject-Level Sensitivity Analysis (표본 크기: <span class="math inline">\(N=98\)</span> [HC=21, PD=77])</strong>: * 동일 피험자의 다회 측정값을 산술 평균화할 시 분산이 인위적으로 압축되는 편향을 피하기 위해, 본 분석에서는 피험자별로 <strong>무작위 1개 시도만 선택(Random 1-Pick per Subject)</strong>하여 표본의 완전한 독립성과 자연스러운 분산 구조를 보장한 상태에서 가설 검정을 재수행하였습니다. (재현성 확보를 위해 난수 시드 <code>random_state=42</code> 적용)</p>
</section>
<section id="통계-검정-및-효과-크기-평측-방법" class="level3">
<h3 class="anchored" data-anchor-id="통계-검정-및-효과-크기-평측-방법">2-2. 통계 검정 및 효과 크기 평측 방법</h3>
<ul>
<li><strong>가설 검정</strong>: 두 집단 간의 이분산성을 고려한 <strong>Welch’s t-test</strong>와 비모수적 순위 대조 검정인 <strong>Mann-Whitney U test</strong>를 병행 수행하였습니다.</li>
<li><strong>효과 크기 (Effect Size)</strong>: 두 집단의 표준화된 차이 강도를 측정하기 위해 <strong>Cohen’s <span class="math inline">\(d\)</span></strong>를 계산하였으며, 평균 차이의 <strong>95% 신뢰구간(95% Confidence Interval, CI)</strong>을 Welch-Satterthwaite 자유도를 활용해 산출하였습니다.</li>
<li><strong>다중 검정 보정 (Multiple Comparison Correction)</strong>: 6대 종속 변수의 동시 검정에 따른 오류 발생 확률을 제어하기 위해 <strong>Bonferroni 보정</strong> 및 <strong>Benjamini-Hochberg FDR(False Discovery Rate) 보정</strong>을 일괄 적용하여 보정 후 p-value를 추가 보고합니다. 유의수준은 <span class="math inline">\(\alpha = 0.05\)</span>로 설정하였습니다.</li>
</ul>
<hr>
</section>
</section>
<section id="results-통계-검정-결과" class="level2">
<h2 class="anchored" data-anchor-id="results-통계-검정-결과">3. Results (통계 검정 결과)</h2>
<section id="table-1.-trial-level-comparison-primary-analysis-n233-trials" class="level3">
<h3 class="anchored" data-anchor-id="table-1.-trial-level-comparison-primary-analysis-n233-trials">Table 1. Trial-Level Comparison (Primary Analysis, <span class="math inline">\(N=233\)</span> trials)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">보행 변수 (Gait Metric)</th>
<th style="text-align: center;">정상 대조군 (HC)<br>(<span class="math inline">\(n=40\)</span> trials)</th>
<th style="text-align: center;">파킨슨 환자군 (PD)<br>(<span class="math inline">\(n=193\)</span> trials)</th>
<th style="text-align: center;">효과 크기<br>(Cohen’s <span class="math inline">\(d\)</span>)</th>
<th style="text-align: center;">평균 차이 95% CI<br>(MD [95% CI])</th>
<th style="text-align: center;">Welch’s t-test p-value<br>(raw / Bonferroni / FDR)</th>
<th style="text-align: center;">Mann-Whitney U p-value<br>(raw / Bonferroni / FDR)</th>
<th style="text-align: left;">귀무가설 (<span class="math inline">\(H_0\)</span>) 기각 여부<br>(at <span class="math inline">\(\alpha=0.05\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Stride Time (s)</strong></td>
<td style="text-align: center;"><span class="math inline">\(1.053 \pm 0.120\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1.043 \pm 0.090\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.102\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.010\ [-0.051, 0.031]\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.6289\ /\ 1.0000\ /\ 0.7546\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.8629\ /\ 1.0000\ /\ 0.9158\)</span></td>
<td style="text-align: left;">기각 안 됨</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Stride Time CV</strong></td>
<td style="text-align: center;"><span class="math inline">\(0.085 \pm 0.130\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.068 \pm 0.049\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.236\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.017\ [-0.059, 0.026]\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.4374\ /\ 1.0000\ /\ 0.6561\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.5768\ /\ 1.0000\ /\ 0.8653\)</span></td>
<td style="text-align: left;">기각 안 됨</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Step Length (m)</strong></td>
<td style="text-align: center;"><span class="math inline">\(0.663 \pm 0.078\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.575 \pm 0.098\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.922\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.088\ [-0.116, -0.059]\)</span></td>
<td style="text-align: center;"><strong><span class="math inline">\(5.738\times 10^{-8}\)</span></strong> / <strong><span class="math inline">\(3.443\times 10^{-7}\)</span></strong> / <strong><span class="math inline">\(3.443\times 10^{-7}\)</span></strong></td>
<td style="text-align: center;"><strong><span class="math inline">\(1.088\times 10^{-6}\)</span></strong> / <strong><span class="math inline">\(6.526\times 10^{-6}\)</span></strong> / <strong><span class="math inline">\(6.526\times 10^{-6}\)</span></strong></td>
<td style="text-align: left;"><strong>기각 됨 (유의함)</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Gait Speed (m/s)</strong></td>
<td style="text-align: center;"><span class="math inline">\(1.221 \pm 0.269\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1.085 \pm 0.206\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.622\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.136\ [-0.228, -0.045]\)</span></td>
<td style="text-align: center;"><strong><span class="math inline">\(0.0043\ /\ 0.0260\ /\ 0.0130\)</span></strong></td>
<td style="text-align: center;"><strong><span class="math inline">\(0.0001\ /\ 0.0006\ /\ 0.0003\)</span></strong></td>
<td style="text-align: left;"><strong>기각 됨 (유의함)</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Cadence (steps/min)</strong></td>
<td style="text-align: center;"><span class="math inline">\(114.561 \pm 9.905\)</span></td>
<td style="text-align: center;"><span class="math inline">\(115.038 \pm 9.717\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.049\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.476\ [-2.998, 3.951]\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.7845\ /\ 1.0000\ /\ 0.7845\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.9158\ /\ 1.0000\ /\ 0.9158\)</span></td>
<td style="text-align: left;">기각 안 됨</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Initiation Delay (s)</strong></td>
<td style="text-align: center;"><span class="math inline">\(0.707 \pm 0.786\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.865 \pm 0.941\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.172\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.158\ [-0.127, 0.444]\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.2721\ /\ 1.0000\ /\ 0.5442\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.1797\ /\ 1.0000\ /\ 0.3595\)</span></td>
<td style="text-align: left;">기각 안 됨</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="table-2.-subject-level-comparison-sensitivity-analysis-random-1-pick-n98-subjects" class="level3">
<h3 class="anchored" data-anchor-id="table-2.-subject-level-comparison-sensitivity-analysis-random-1-pick-n98-subjects">Table 2. Subject-Level Comparison (Sensitivity Analysis, Random 1-Pick, <span class="math inline">\(N=98\)</span> subjects)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">보행 변수 (Gait Metric)</th>
<th style="text-align: center;">정상 대조군 (HC)<br>(<span class="math inline">\(n=21\)</span> subjects)</th>
<th style="text-align: center;">파킨슨 환자군 (PD)<br>(<span class="math inline">\(n=77\)</span> subjects)</th>
<th style="text-align: center;">효과 크기<br>(Cohen’s <span class="math inline">\(d\)</span>)</th>
<th style="text-align: center;">평균 차이 95% CI<br>(MD [95% CI])</th>
<th style="text-align: center;">Welch’s t-test p-value<br>(raw / Bonferroni / FDR)</th>
<th style="text-align: center;">Mann-Whitney U p-value<br>(raw / Bonferroni / FDR)</th>
<th style="text-align: left;">귀무가설 (<span class="math inline">\(H_0\)</span>) 기각 여부<br>(at <span class="math inline">\(\alpha=0.05\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Stride Time (s)</strong></td>
<td style="text-align: center;"><span class="math inline">\(1.047 \pm 0.084\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1.041 \pm 0.094\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.069\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.006\ [-0.050, 0.038]\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.7700\ /\ 1.0000\ /\ 0.9939\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.7194\ /\ 1.0000\ /\ 0.8827\)</span></td>
<td style="text-align: left;">기각 안 됨</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Stride Time CV</strong></td>
<td style="text-align: center;"><span class="math inline">\(0.069 \pm 0.076\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.069 \pm 0.043\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.013\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.001\ [-0.037, 0.036]\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.9697\ /\ 1.0000\ /\ 0.9939\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.3819\ /\ 1.0000\ /\ 0.7637\)</span></td>
<td style="text-align: left;">기각 안 됨</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Step Length (m)</strong></td>
<td style="text-align: center;"><span class="math inline">\(0.675 \pm 0.075\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.580 \pm 0.096\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-1.028\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.095\ [-0.135, -0.055]\)</span></td>
<td style="text-align: center;"><strong><span class="math inline">\(2.752\times 10^{-5}\)</span></strong> / <strong><span class="math inline">\(1.651\times 10^{-4}\)</span></strong> / <strong><span class="math inline">\(1.651\times 10^{-4}\)</span></strong></td>
<td style="text-align: center;"><strong><span class="math inline">\(4.217\times 10^{-5}\)</span></strong> / <strong><span class="math inline">\(2.530\times 10^{-4}\)</span></strong> / <strong><span class="math inline">\(2.530\times 10^{-4}\)</span></strong></td>
<td style="text-align: left;"><strong>기각 됨 (유의함)</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Gait Speed (m/s)</strong></td>
<td style="text-align: center;"><span class="math inline">\(1.267 \pm 0.225\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1.099 \pm 0.205\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.793\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.168\ [-0.282, -0.055]\)</span></td>
<td style="text-align: center;"><strong><span class="math inline">\(0.0051\ /\ 0.0306\ /\ 0.0153\)</span></strong></td>
<td style="text-align: center;"><strong><span class="math inline">\(0.0019\ /\ 0.0116\ /\ 0.0058\)</span></strong></td>
<td style="text-align: left;"><strong>기각 됨 (유의함)</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Cadence (steps/min)</strong></td>
<td style="text-align: center;"><span class="math inline">\(114.691 \pm 8.643\)</span></td>
<td style="text-align: center;"><span class="math inline">\(115.121 \pm 10.023\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.044\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.430\ [-4.133, 4.993]\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.8495\ /\ 1.0000\ /\ 0.9939\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.7356\ /\ 1.0000\ /\ 0.8827\)</span></td>
<td style="text-align: left;">기각 안 됨</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Initiation Delay (s)</strong></td>
<td style="text-align: center;"><span class="math inline">\(0.780 \pm 0.819\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.779 \pm 0.804\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.002\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.002\ [-0.420, 0.417]\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.9939\ /\ 1.0000\ /\ 0.9939\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.9517\ /\ 1.0000\ /\ 0.9517\)</span></td>
<td style="text-align: left;">기각 안 됨</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="각-변수별-가설-검정-결과의-통계적-상세-기술" class="level3">
<h3 class="anchored" data-anchor-id="각-변수별-가설-검정-결과의-통계적-상세-기술">3-1. 각 변수별 가설 검정 결과의 통계적 상세 기술</h3>
<p>본 절에서는 제시된 Table 1(시도 수준)과 Table 2(무작위 1픽 피험자 수준)의 모든 통계 평측치(집단별 평균/표준편차, 효과 크기 Cohen’s <span class="math inline">\(d\)</span>, 평균 차이의 95% 신뢰구간, Welch’s t-test 및 Mann-Whitney U 검정의 원시/Bonferroni/FDR 보정 p-value)를 변수별로 교차하여 체계적으로 기술합니다.</p>
<section id="stride-time-보폭-주기-시간" class="level4">
<h4 class="anchored" data-anchor-id="stride-time-보폭-주기-시간">1) Stride Time (보폭 주기 시간)</h4>
<ul>
<li><strong>시도 수준 (Trial-Level)</strong>: 정상 대조군(<span class="math inline">\(1.053 \pm 0.120\text{ s}\)</span>)과 파킨슨 환자군(<span class="math inline">\(1.043 \pm 0.090\text{ s}\)</span>)의 평균 차이는 <span class="math inline">\(-0.010\text{ s}\)</span>이며, 이 차이의 95% 신뢰구간은 <span class="math inline">\([-0.051, 0.031]\text{ s}\)</span>로 산출되었습니다. 집단 간 효과 크기는 Cohen’s <span class="math inline">\(d = -0.102\)</span>로 매우 낮았습니다. Welch’s t-test p-value는 raw <span class="math inline">\(p=0.6289\)</span>, Bonferroni 보정 <span class="math inline">\(p=1.0000\)</span>, FDR 보정 <span class="math inline">\(p=0.7546\)</span>이었으며, Mann-Whitney U 검정 p-value 역시 raw <span class="math inline">\(p=0.8629\)</span>, Bonferroni 보정 <span class="math inline">\(p=1.0000\)</span>, FDR 보정 <span class="math inline">\(p=0.9158\)</span>로 집단 간 유의미한 시간적 차이가 발견되지 않았습니다.</li>
<li><strong>피험자 수준 (Subject-Level, Random 1-Pick)</strong>: 피험자별 무작위 1개 시도 선택 대조에서 정상 대조군(<span class="math inline">\(1.047 \pm 0.084\text{ s}\)</span>)과 파킨슨 환자군(<span class="math inline">\(1.041 \pm 0.094\text{ s}\)</span>)의 평균 차이는 <span class="math inline">\(-0.006\text{ s}\)</span> (95% CI: <span class="math inline">\([-0.050, 0.038]\text{ s}\)</span>)였으며, 효과 크기는 <span class="math inline">\(d = -0.069\)</span>로 극히 낮았습니다. 가설 검정 결과 Welch’s t-test p-value는 raw <span class="math inline">\(p=0.7700\)</span>, Bonferroni 보정 <span class="math inline">\(p=1.0000\)</span>, FDR 보정 <span class="math inline">\(p=0.9939\)</span>였고, MWU 검정 p-value 역시 raw <span class="math inline">\(p=0.7194\)</span>, Bonferroni 보정 <span class="math inline">\(p=1.0000\)</span>, FDR 보정 <span class="math inline">\(p=0.8827\)</span>로 통계적 유의성이 완전히 부재하였습니다.</li>
</ul>
</section>
<section id="stride-time-variability-보폭-주기-변동성-cv" class="level4">
<h4 class="anchored" data-anchor-id="stride-time-variability-보폭-주기-변동성-cv">2) Stride Time Variability (보폭 주기 변동성, CV)</h4>
<ul>
<li><strong>시도 수준 (Trial-Level)</strong>: 정상 대조군(<span class="math inline">\(0.085 \pm 0.130\)</span>) 대비 파킨슨 환자군(<span class="math inline">\(0.068 \pm 0.049\)</span>)의 평균 변동계수 차이는 <span class="math inline">\(-0.017\)</span> (95% CI: <span class="math inline">\([-0.059, 0.026]\)</span>)이었으며, 효과 크기는 <span class="math inline">\(d = -0.236\)</span>으로 나타났습니다. Welch’s t-test p-value는 raw <span class="math inline">\(p=0.4374\)</span>, Bonferroni 보정 <span class="math inline">\(p=1.0000\)</span>, FDR 보정 <span class="math inline">\(p=0.6561\)</span>이었으며, MWU 검정 p-value는 raw <span class="math inline">\(p=0.5768\)</span>, Bonferroni 보정 <span class="math inline">\(p=1.0000\)</span>, FDR 보정 <span class="math inline">\(p=0.8653\)</span>으로 유의수준에 도달하지 못했습니다.</li>
<li><strong>피험자 수준 (Subject-Level, Random 1-Pick)</strong>: 피험자별 무작위 1개 시도 선택 대조에서 정상 대조군(<span class="math inline">\(0.069 \pm 0.076\)</span>)과 파킨슨 환자군(<span class="math inline">\(0.069 \pm 0.043\)</span>)의 평균 차이는 <span class="math inline">\(-0.001\)</span> (95% CI: <span class="math inline">\([-0.037, 0.036]\)</span>)이었고, 효과 크기는 <span class="math inline">\(d = -0.013\)</span>으로 사실상 차이가 없었습니다. 가설 검정 결과 Welch’s t-test p-value는 raw <span class="math inline">\(p=0.9697\)</span>, Bonferroni 보정 <span class="math inline">\(p=1.0000\)</span>, FDR 보정 <span class="math inline">\(p=0.9939\)</span>였으며, MWU 검정 p-value는 raw <span class="math inline">\(p=0.3819\)</span>, Bonferroni 보정 <span class="math inline">\(p=1.0000\)</span>, FDR 보정 <span class="math inline">\(p=0.7637\)</span>로 통계적 유의성이 전혀 관찰되지 않았습니다.</li>
</ul>
</section>
<section id="step-length-걸음-길이" class="level4">
<h4 class="anchored" data-anchor-id="step-length-걸음-길이">3) Step Length (걸음 길이)</h4>
<ul>
<li><strong>시도 수준 (Trial-Level)</strong>: 정상 대조군(<span class="math inline">\(0.663 \pm 0.078\text{ m}\)</span>) 대비 파킨슨 환자군(<span class="math inline">\(0.575 \pm 0.098\text{ m}\)</span>)에서 걸음 길이는 평균 <span class="math inline">\(-0.088\text{ m}\)</span> 단축되었습니다. 평균 차이의 95% 신뢰구간은 <span class="math inline">\([-0.116, -0.059]\text{ m}\)</span>으로 강건한 음의 변량을 나타냈고, 효과 크기는 Cohen’s <span class="math inline">\(d = -0.922\)</span>로 고도의 생체역학적 격차를 나타냈습니다. Welch’s t-test p-value는 raw <span class="math inline">\(p=5.738\times 10^{-8}\)</span>, Bonferroni 보정 <span class="math inline">\(p=3.443\times 10^{-7}\)</span>, FDR 보정 <span class="math inline">\(p=3.443\times 10^{-7}\)</span>이었으며, MWU 검정 p-value 역시 raw <span class="math inline">\(p=1.088\times 10^{-6}\)</span>, Bonferroni 보정 <span class="math inline">\(p=6.526\times 10^{-6}\)</span>, FDR 보정 <span class="math inline">\(p=6.526\times 10^{-6}\)</span>으로 다중 비교 보정 적용 여부와 관계없이 모두 극도로 유의미하였습니다.</li>
<li><strong>피험자 수준 (Subject-Level, Random 1-Pick)</strong>: 피험자별 무작위 1개 시도 선택 대조에서 정상 대조군(<span class="math inline">\(0.675 \pm 0.075\text{ m}\)</span>) 대비 파킨슨 환자군(<span class="math inline">\(0.580 \pm 0.096\text{ m}\)</span>)의 평균 차이는 <span class="math inline">\(-0.095\text{ m}\)</span> (95% CI: <span class="math inline">\([-0.135, -0.055]\text{ m}\)</span>)였으며, 효과 크기는 <span class="math inline">\(d = -1.028\)</span>로 매우 강력한 차이를 보였습니다. 가설 검정 결과 Welch’s t-test p-value는 raw <span class="math inline">\(p=2.752\times 10^{-5}\)</span>, Bonferroni 보정 <span class="math inline">\(p=1.651\times 10^{-4}\)</span>, FDR 보정 <span class="math inline">\(p=1.651\times 10^{-4}\)</span>였고, MWU 검정 p-value는 raw <span class="math inline">\(p=4.217\times 10^{-5}\)</span>, Bonferroni 보정 <span class="math inline">\(p=2.530\times 10^{-4}\)</span>, FDR 보정 <span class="math inline">\(p=2.530\times 10^{-4}\)</span>로 피험자 독립성과 자연스러운 개별 분산을 확보한 후에도 고도의 통계적 유의성을 일관되게 입증하였습니다.</li>
</ul>
</section>
<section id="gait-speed-보행-속도" class="level4">
<h4 class="anchored" data-anchor-id="gait-speed-보행-속도">4) Gait Speed (보행 속도)</h4>
<ul>
<li><strong>시도 수준 (Trial-Level)</strong>: 정상 대조군(<span class="math inline">\(1.221 \pm 0.269\text{ m/s}\)</span>) 대비 파킨슨 환자군(<span class="math inline">\(1.085 \pm 0.206\text{ m/s}\)</span>)의 속도 차이는 평균 <span class="math inline">\(-0.136\text{ m/s}\)</span> (95% CI: <span class="math inline">\([-0.228, -0.045]\text{ m/s}\)</span>)로 유의하게 저하되었습니다. 집단 간 효과 크기는 Cohen’s <span class="math inline">\(d = -0.622\)</span>로 중간 강도 이상의 효율 감퇴를 보였으며, Welch’s t-test p-value는 raw <span class="math inline">\(p=0.0043\)</span>, Bonferroni 보정 <span class="math inline">\(p=0.0260\)</span>, FDR 보정 <span class="math inline">\(p=0.0130\)</span>이었고, MWU 검정 p-value는 raw <span class="math inline">\(p=0.0001\)</span>, Bonferroni 보정 <span class="math inline">\(p=0.0006\)</span>, FDR 보정 <span class="math inline">\(p=0.0003\)</span>으로 통계적 유의성이 검증되었습니다.</li>
<li><strong>피험자 수준 (Subject-Level, Random 1-Pick)</strong>: 피험자별 무작위 1개 시도 선택 대조에서 정상 대조군(<span class="math inline">\(1.267 \pm 0.225\text{ m/s}\)</span>) 대비 파킨슨 환자군(<span class="math inline">\(1.099 \pm 0.205\text{ m/s}\)</span>)의 평균 속도 차이는 <span class="math inline">\(-0.168\text{ m/s}\)</span> (95% CI: <span class="math inline">\([-0.282, -0.055]\text{ m/s}\)</span>)였으며, 효과 크기는 <span class="math inline">\(d = -0.793\)</span>으로 높은 감퇴 폭을 나타냈습니다. 가설 검정 결과 Welch’s t-test p-value는 raw <span class="math inline">\(p=0.0051\)</span>, Bonferroni 보정 <span class="math inline">\(p=0.0306\)</span>, FDR 보정 <span class="math inline">\(p=0.0153\)</span>이었고, MWU 검정 p-value는 raw <span class="math inline">\(p=0.0019\)</span>, Bonferroni 보정 <span class="math inline">\(p=0.0116\)</span>, FDR 보정 <span class="math inline">\(p=0.0058\)</span>로 다중 검정 보정 후에도 모두 <span class="math inline">\(p &lt; 0.05\)</span> 기준 하에 통계적으로 유의미한 집단 간 속도 차이를 강력하게 보존하였습니다.</li>
</ul>
</section>
<section id="cadence-분당-걸음-수" class="level4">
<h4 class="anchored" data-anchor-id="cadence-분당-걸음-수">5) Cadence (분당 걸음 수)</h4>
<ul>
<li><strong>시도 수준 (Trial-Level)</strong>: 정상 대조군(<span class="math inline">\(114.561 \pm 9.905\text{ steps/min}\)</span>)과 파킨슨군(<span class="math inline">\(115.038 \pm 9.717\text{ steps/min}\)</span>)의 평균 차이는 <span class="math inline">\(0.476\text{ steps/min}\)</span> (95% CI: <span class="math inline">\([-2.998, 3.951]\text{ steps/min}\)</span>)으로 사실상 대등하였으며, 효과 크기는 Cohen’s <span class="math inline">\(d = 0.049\)</span>에 불과했습니다. Welch’s t-test p-value는 raw <span class="math inline">\(p=0.7845\)</span>, Bonferroni 보정 <span class="math inline">\(p=1.0000\)</span>, FDR 보정 <span class="math inline">\(p=0.7845\)</span>였으며, MWU 검정 p-value 역시 raw <span class="math inline">\(p=0.9158\)</span>, Bonferroni 보정 <span class="math inline">\(p=1.0000\)</span>, FDR 보정 <span class="math inline">\(p=0.9158\)</span>로 유의미하지 않았습니다.</li>
<li><strong>피험자 수준 (Subject-Level, Random 1-Pick)</strong>: 피험자별 무작위 1개 시도 선택 대조에서도 정상 대조군(<span class="math inline">\(114.691 \pm 8.643\text{ steps/min}\)</span>)과 파킨슨군(<span class="math inline">\(115.121 \pm 10.023\text{ steps/min}\)</span>)의 평균 차이는 <span class="math inline">\(0.430\text{ steps/min}\)</span> (95% CI: <span class="math inline">\([-4.133, 4.993]\text{ steps/min}\)</span>)였고, 효과 크기는 <span class="math inline">\(d = 0.044\)</span>에 그쳤습니다. 가설 검정 결과 Welch’s t-test p-value는 raw <span class="math inline">\(p=0.8495\)</span>, Bonferroni 보정 <span class="math inline">\(p=1.0000\)</span>, FDR 보정 <span class="math inline">\(p=0.9939\)</span>였고, MWU 검정 p-value는 raw <span class="math inline">\(p=0.7356\)</span>, Bonferroni 보정 <span class="math inline">\(p=1.0000\)</span>, FDR 보정 <span class="math inline">\(p=0.8827\)</span>로 통계적 유의성이 완전히 부재하였습니다.</li>
</ul>
</section>
<section id="initiation-delay-보행-개시-지연" class="level4">
<h4 class="anchored" data-anchor-id="initiation-delay-보행-개시-지연">6) Initiation Delay (보행 개시 지연)</h4>
<ul>
<li><strong>시도 수준 (Trial-Level)</strong>: 정상 대조군(<span class="math inline">\(0.707 \pm 0.786\text{ s}\)</span>) 대비 파킨슨군(<span class="math inline">\(0.865 \pm 0.941\text{ s}\)</span>)의 보행 시작 지연 시간 평균 차이는 <span class="math inline">\(0.158\text{ s}\)</span> (95% CI: <span class="math inline">\([-0.127, 0.444]\text{ s}\)</span>)로 절대치는 증가했으나 효과 크기는 <span class="math inline">\(d = 0.172\)</span>로 미약했습니다. 가설 검정 결과 Welch’s t-test p-value는 raw <span class="math inline">\(p=0.2721\)</span>, Bonferroni 보정 <span class="math inline">\(p=1.0000\)</span>, FDR 보정 <span class="math inline">\(p=0.5442\)</span>였고, MWU 검정 p-value는 raw <span class="math inline">\(p=0.1797\)</span>, Bonferroni 보정 <span class="math inline">\(p=1.0000\)</span>, FDR 보정 <span class="math inline">\(p=0.3595\)</span>로 통계적 유의수준에 도달하지 못했습니다.</li>
<li><strong>피험자 수준 (Subject-Level, Random 1-Pick)</strong>: 피험자별 무작위 1개 시도 선택 대조에서 정상 대조군(<span class="math inline">\(0.780 \pm 0.819\text{ s}\)</span>) 대비 파킨슨군(<span class="math inline">\(0.779 \pm 0.804\text{ s}\)</span>)의 평균 차이는 <span class="math inline">\(-0.002\text{ s}\)</span> (95% CI: <span class="math inline">\([-0.420, 0.417]\text{ s}\)</span>)로 사실상 소멸하였으며 효과 크기 또한 <span class="math inline">\(d = -0.002\)</span>로 영에 수렴하였습니다. 가설 검정 결과 Welch’s t-test p-value는 raw <span class="math inline">\(p=0.9939\)</span>, Bonferroni 보정 <span class="math inline">\(p=1.0000\)</span>, FDR 보정 <span class="math inline">\(p=0.9939\)</span>이었으며, MWU 검정 p-value 역시 raw <span class="math inline">\(p=0.9517\)</span>, Bonferroni 보정 <span class="math inline">\(p=1.0000\)</span>, FDR 보정 <span class="math inline">\(p=0.9517\)</span>로 집단 간 어떠한 통계적 격차도 관찰되지 않았습니다.</li>
</ul>
<hr>
</section>
</section>
<section id="가설-검정-결과-테이블의-총체적-해석" class="level3">
<h3 class="anchored" data-anchor-id="가설-검정-결과-테이블의-총체적-해석">3-2. 가설 검정 결과 테이블의 총체적 해석</h3>
<p>제시된 통계 데이터의 다각적인 평측 결과는 본 표준 6m 보행 프로토콜 하에서 파킨슨 환자군이 가지는 보행 병리의 <strong>“시간적 보존성과 공간적 감퇴성”</strong>을 매우 뚜렷하고 강건하게 나타냅니다.</p>
<p>첫째, <strong>걸음 길이(Step Length)는 피험자별 다회 측정에 따른 분산 압축 오류를 완전히 배제한 무작위 1픽 피험자 수준(Subject-level) 분석에서도 <span class="math inline">\(0.0003\)</span> 미만의 Bonferroni 보정 유의확률과 <span class="math inline">\(-1.028\)</span>에 달하는 압도적인 효과 크기(<span class="math inline">\(d\)</span>)를 나타냈습니다.</strong> 이는 짧은 직선 보행 경로 환경에서 파킨슨 환자군이 대조군과 구별되는 가장 신뢰성 높고 뚜렷한 운동학적 변별 특징이 공간적 보폭 감퇴임을 수학적으로 실증합니다.</p>
<p>둘째, <strong>보행 주기 시간(Stride Time)과 분당 걸음 수(Cadence)의 경우, 통계적 유의확률이 일관되게 유의기준선을 현저히 초과(<span class="math inline">\(p \ge 0.60\)</span>)하며 귀무가설 기각에 철저히 실패하였습니다.</strong> 두 시간적 변수의 높은 대등성은 보행 속도(Gait Speed)가 느려진 기전이 발을 딛는 박자나 신경학적 주파수의 지연에 있는 것이 아니라, 오직 물리적 보폭 단축(Step Length)이라는 단일 공간 기하학 변수의 왜곡에 의한 대수적 결과임을 증명합니다.</p>
<p>셋째, <strong>보행 속도(Gait Speed)는 피험자 평균화 방식을 배제하고 본연의 내재적 분산을 그대로 노출시킨 무작위 1픽 피험자 검정(Table 2)에서도 Welch p = 0.0051 (Bonferroni 보정 p = 0.0306), MWU p = 0.0019 (Bonferroni 보정 p = 0.0116)로 고도의 통계적 유의성을 일관되게 보존하였습니다.</strong> 이는 평균화에 따른 왜곡을 피하기 위해 임의의 1개 시도만을 채택했음에도 효과 크기가 <span class="math inline">\(d = -0.793\)</span>으로 강력하여 공간적 단축이 속도 감소로 직결되는 현상의 강인성(Robustness)을 보여주는 결정적 증거입니다.</p>
<p>넷째, <strong>Stride Time CV 및 Initiation Delay의 Null 결과는 본 walk-through 실험 모델이 가진 내재적 한계를 통계적으로 방증합니다.</strong> 특히 피험자 수준 1픽 대조 시 Initiation Delay의 효과 크기는 <span class="math inline">\(d = -0.002\)</span>로 사실상 영에 수렴하였으며, 이는 개시 타이밍 변수가 6m 단순 walk-through 프로토콜 내에서 정지 대기 상태 통제 결여 및 가속 시작 궤적 노이즈로 인해 파킨슨 진단을 위한 스크리닝 바이오마커로 성립될 수 없음을 최종적으로 방증합니다.</p>
<hr>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">4. Discussion</h2>
<section id="공간적spatial-결함의-확실성-및-대수적-인과관계-규명" class="level3">
<h3 class="anchored" data-anchor-id="공간적spatial-결함의-확실성-및-대수적-인과관계-규명">4-1. 공간적(Spatial) 결함의 확실성 및 대수적 인과관계 규명</h3>
<p>본 분석의 두 가설 검정 테이블은 정상군과 파킨슨군 간의 <strong>공간적 거동(Step Length) 단축</strong>을 매우 일관되고 강력하게 지지하고 있습니다. * <strong>걸음 길이 (Step Length)</strong>: 시도 단위 검정(Cohen’s <span class="math inline">\(d = -0.922\)</span>, Bonferroni 보정 <span class="math inline">\(p &lt; 10^{-6}\)</span>)과 피험자 단위 검정(Cohen’s <span class="math inline">\(d = -1.028\)</span>, Bonferroni 보정 <span class="math inline">\(p &lt; 0.001\)</span>) 모두에서 극도로 뚜렷한 통계적 유의차가 확보되었습니다. 파킨슨 환자는 정상군 대비 약 8.8cm 짧은 걸음걸이를 보입니다. * <strong>보행 속도 (Gait Speed)</strong>: 보행 속도는 <span class="math inline">\(\text{Speed} \approx \text{Step Length} \times \frac{\text{Cadence}}{60}\)</span>의 물리적 대수식으로 구성됩니다. 분당 걸음 수(Cadence, <span class="math inline">\(p \ge 0.60\)</span>)가 집단 간 통계적으로 완전히 대등한 리듬을 유지하고 있음에도 속도가 유의미하게 저하된 것은(Trial Welch p = 0.0043), <strong>시간적 템포의 상실이 아닌 공간적 보폭(Step Length)의 물리적 감소만이 보행 속도 저하를 유발하는 핵심 독립 인자</strong>임을 의미합니다.</p>
</section>
<section id="이중-분석dual-level-analysis의-가치-및-보행-속도의-경계선-유의미성" class="level3">
<h3 class="anchored" data-anchor-id="이중-분석dual-level-analysis의-가치-및-보행-속도의-경계선-유의미성">4-2. 이중 분석(Dual-level Analysis)의 가치 및 보행 속도의 경계선 유의미성</h3>
<p>피험자 수준 무작위 1픽(Table 2)으로 데이터를 전처리하여 분석했을 때에도 <code>Gait Speed</code>와 <code>Step Length</code>는 통계적 유의성을 강력하게 유지하여, 시도 단위 분석의 다회 측정 상관관계 과대 추정 위협을 완벽히 방어해냈습니다. 이 이중 구조 비교는 6m 짧은 보행 프로토콜에서 평균화 필터에 의한 인위적인 분산 압축 왜곡을 배제하고도, 파킨슨 환자군이 가지는 보행 병리적 특성을 편향 없이 입증해 낼 수 있는 설계적 모범을 제시합니다.</p>
</section>
<section id="stride-time-cv의-통계적-null-결과와-방향성-전도-현상" class="level3">
<h3 class="anchored" data-anchor-id="stride-time-cv의-통계적-null-결과와-방향성-전도-현상">4-3. Stride Time CV의 통계적 Null 결과와 방향성 전도 현상</h3>
<p>본 분석에서 Stride Time CV는 대조군이 오히려 파킨슨군보다 큰 값을 기록(HC: 0.085 vs PD: 0.068)하며 기각되지 않았습니다 (<span class="math inline">\(p \ge 0.40\)</span>). 파킨슨병의 전형적인 보행 리듬 불규칙성(PD &gt; HC) 문헌 예측과 반대로 나타난 원인은 다음과 같이 분석적 한계로 설명됩니다. 1. <strong>단거리 가감속 과도기의 높은 비중</strong>: 6m 보행은 거리가 매우 짧아 정상 보행 리듬이 유지되는 정상상태(Steady-state) 구간에 비해 출발 시 가속과 종료 시 감속이 차지하는 비율이 높습니다. 정상 대조군의 경우 높은 민첩성으로 인해 자발적으로 가속과 감속 폭을 역동적으로 조절함으로써 Stride Time의 변동 폭이 과대 추정되었습니다. 2. <strong>소표본 Stride 수에 의한 하향 편향 (Small Sample Bias)</strong>: 변동계수(CV)는 검출된 Stride의 수(<span class="math inline">\(N\)</span>)가 작을 때 계수가 과소 추정되는 하향 편향이 강하게 작용합니다. 짧은 보폭을 가진 파킨슨 환자는 6m 구간 내에 검출된 Stride 수가 정상군에 비해 유의하게 작아, 통계 연산 구조상 환자군의 CV가 인위적으로 과소평가되는 분석 왜곡이 개입되었을 가능성이 큽니다.</p>
</section>
<section id="initiation-delay-null-결과의-설계적-해석" class="level3">
<h3 class="anchored" data-anchor-id="initiation-delay-null-결과의-설계적-해석">4-4. Initiation Delay Null 결과의 설계적 해석</h3>
<p>가설 검정에서 Initiation Delay는 집단 간 유의미한 차이를 나타내지 않았습니다 (<span class="math inline">\(p \ge 0.16\)</span>). 본 6m walk-through 프로토콜은 정지 대기 상태에서 가속 및 개시 신호에 대한 인지적/운동적 타이밍 통제를 사전에 규정하지 않았습니다. 따라서 가동 개시를 판정하는 골반 2cm 돌파 시점(<span class="math inline">\(t_{\text{onset}}\)</span>)은 정적 대기 중 피험자의 미세 흔들림이나 준비 동작(Anticipatory Postural Adjustment, APA)의 노이즈 변동성에 크게 노출됩니다. 이 Null 결과는 지표의 결함이라기보다, 정지 자세 통제가 배제된 <strong>단순 6m walk-through 스크리닝 프로토콜이 가질 수 있는 초기 거동 시작 상태에 대한 판정 감도의 한계</strong>를 명시적으로 나타내는 Findings입니다.</p>
<hr>
</section>
</section>
<section id="conclusion-future-work-결론-및-향후-보완-방향" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-future-work-결론-및-향후-보완-방향">5. Conclusion &amp; Future Work (결론 및 향후 보완 방향)</h2>
<p>다기관 모션 캡처 데이터셋 분석을 통해 6m 공간 범위 및 Step Alignment 처리를 거친 보행 특징 변수의 진단 타당성을 가설 검정하였습니다. 가설 검정 결과, 보행 속도 저하와 보폭 단축 등의 공간적 지표 감퇴가 파킨슨병 보행 특징을 나타내는 주요 요인임을 입증한 반면, 시간적 페이싱(Cadence, Stride Time) 및 정적 상태로부터의 개시 지연은 통계적 차이가 관찰되지 않았습니다.</p>
<p>향후 연구에서는 이러한 통계적 한계를 극복하기 위해 아래 단계를 진행할 것입니다: 1. <strong>피험자 수준 데이터 집계 (Subject-level Aggregation)</strong>: 각 피험자 ID별 반복 측정 시도를 평균 또는 중앙값으로 대표화하여 표본 독립성을 확보한 후 통계 검정을 재검토합니다. 2. <strong>선형 혼합 효과 모델 (Linear Mixed-Effects Model, LMM) 분석</strong>: 반복 측정 데이터의 구조적 종속성을 수학적으로 반영하여 검정력을 고도화할 계획입니다.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button,
        { trigger: "manual",
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config);
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined;
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            }
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          }
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>